project:
  type: website

website:
  title: "VSGS-2026"
  back-to-top-navigation: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Committees"
        href: committees.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Participants"
        href: participants.qmd
      - text: "Venue"
        href: how-to-arrive.qmd

  page-footer: 
    right: Made with [Quarto](https://quarto.org/)
    #right: "Maintenance: the organizers"

format:
  html:
    theme: 
         - sandstone
         # - custom.scss
    css: styles.css
    toc: true
    sidebar: false




